// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OtonohaTouch","status":true,"description":"オトノハのプレイ画面をタッチ操作に対応させる","parameters":{"Number of Buttons":"5","Offset X":"72","Offset Y":"312","Button Width":"96","Button Height":"312","Button Margin":"48","Play Map ID":"2","Input Enabled SW":"343"}}
];
